version: "3.9"
services:
  pzserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: pzserver
#    environment:
#      -
    ports:
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272"
      - "27015:27015"
    volumes:
      - "pzserver_data:/home/steam/pzserver"
volumes:
  pzserver_data:

