version: "3.8"
services:
  pzserver:
    #image: danixu86/project-zomboid-dedicated-server:latest
    build:
      context: .
      dockerfile: dockerfile
    container_name: pzserver
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8766:8766/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272/tcp"
    volumes:
      # Server data
      - ./data:/home/steam/Zomboid
      # Workshop mods folder
      - ./workshop-mods:/home/steam/pz-dedicated/steamapps/workshop
